### ISSUE TITLE
Some warnings and create account failed.

### ISSUE THREAD

**Issue by liuwei-network** [Bramas/hotcrp-docker-compose#2]
Hi, thanks for this repo.

I got some warnings and the registration failed, do you know what is the reason for this?

<img width="1411" alt="image" src="https://user-images.githubusercontent.com/38338565/187061746-fc6b918e-6896-4de1-82b3-a24894d48ec8.png">

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/38338565/187061750-08276b88-3cff-424f-be0b-e223f4010e91.png">

**Comment by Bramas** [comment]
This is due to a bug in hotcrp itself. I checked and saw that it come from the fact that we use PHP 7.4. I fixed the problem and submitted a pull request to hotcrp (https://github.com/kohler/hotcrp/pull/284).
In the meantime you can edit the file "app/lip/dbl.php" and at line 128 replace `assert($this->name);` with `assert(!empty($this->name));`
(this fixes the warnings and the account creation)

Remember that hotcrp is regularly updated, and the last version can have bugs. If you want to use a more stable version, you can start the process but checkout out an old commit after the git clone.

**Comment by liuwei-network** [comment]
Thanks a lot, it works well now.

I still have a small question, I can't receive registration emails, this is my configuration in `.env`, do I need any other configuration for the email?

```
HOTCRP_PAPER_SITE=
# Mandatory: Server address of the SMTP server to use.
SMTP_SERVER=smtp.gmail.com
# Optional: (Default value: 587) Port address of the SMTP server to use.
SMTP_PORT=587
# Mandatory: Username to authenticate with.
SMTP_USERNAME=myname@gmail.com
SMTP_PASSWORD=my apppasswords at https://myaccount.google.com/apppasswords (I have tried my real password, still not work...)
# Mandatory: Server hostname for the Postfix container. Emails will appear to come from the hostname's domain.
SERVER_HOSTNAME=test
```

It may be because my server is in China and it can't use gmail😪, I tried other smtp servers but it still doesn't work.

**Comment by Bramas** [comment]
Hi,
I'm not sure why it is not working (when I tried 4 days ago with another smtp server (not gmail) it was working fine). Maybe the SERVER_HOTNAME should be set to gmail.com
And check the spam folder as well.
You can also see the log, but first you must enable it here https://github.com/Bramas/hotcrp-docker-compose/blob/master/docker-compose.yaml#L27
